services:
  java_app:
    container_name: java_app
    image: aducobu/java-app:1.0.0
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - 8081:8080
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data'

  frontend:
    container_name: frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:8080"
    command: sh -c "npm install -g live-server && live-server --port=8080 --host=0.0.0.0 --open=./index.html"

volumes:
  pgdata: {}