services:
  java_app:
    container_name: java_app
    image: aducobu/java-app:1.0.0
    build:
      context: ./backend
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SPRING_DEVTOOLS_RESTART_TRIGGER_FILE=.restart
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data'

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:8080"
    command: sh -c "npm install -g live-server && live-server --port=8080 --host=0.0.0.0 --open=public/index.html"

volumes:
  pgdata: {}